CREATE TABLE IF NOT EXISTS file_state (
    filename VARCHAR(255) PRIMARY KEY,
    content BLOB,
    checksum CHAR(64),
    size_bytes BIGINT NOT NULL,
    file_version BIGINT NOT NULL,
    deleted BOOLEAN NOT NULL,
    modified_by VARCHAR(64) NOT NULL,
    modified_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT file_state_shape CHECK (
        (deleted = TRUE AND content IS NULL AND checksum IS NULL AND size_bytes = 0)
        OR
        (deleted = FALSE AND content IS NOT NULL AND checksum IS NOT NULL AND size_bytes >= 0)
    )
);

CREATE TABLE IF NOT EXISTS change_log (
    global_version BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    operation VARCHAR(16) NOT NULL,
    content BLOB,
    checksum CHAR(64),
    size_bytes BIGINT NOT NULL,
    client_name VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT change_operation CHECK (
        operation REGEXP '^(CREATE|UPDATE|DELETE)$'
    ),
    CONSTRAINT change_shape CHECK (
        (operation = 'DELETE' AND content IS NULL AND checksum IS NULL AND size_bytes = 0)
        OR
        (operation <> 'DELETE' AND content IS NOT NULL AND checksum IS NOT NULL AND size_bytes >= 0)
    )
);

CREATE TABLE IF NOT EXISTS operation_receipt (
    operation_id UUID PRIMARY KEY,
    outcome VARCHAR(32) NOT NULL,
    requested_filename VARCHAR(255) NOT NULL,
    accepted_filename VARCHAR(255) NOT NULL,
    global_version BIGINT,
    file_version BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT receipt_outcome CHECK (
        outcome REGEXP '^(APPLIED|CONFLICT_COPY_CREATED|DUPLICATE|CONFLICT_REJECTED)$'
    )
);

CREATE INDEX IF NOT EXISTS idx_change_log_version ON change_log(global_version);
